version: '3.8'
services:
  publicapi:
    build:
      context: ./PublicApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  paymentprocessor:
    build:
      context: ./PaymentProcessor
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: GeoPagos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  test:
    build:
      context: ./Test
      dockerfile: Dockerfile
    depends_on:
      - publicapi
