services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: GeoPagos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  test:
    build:
      context: .
      dockerfile: ./TestPaymentProcessorApp/Dockerfile
    depends_on:
      - db
