services:
  publicapi:
    build:
      context: ./PublicApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - PAYMENT_PROCESSOR_URI=${PAYMENT_PROCESSOR_URI}
    depends_on:
      - db
      - rabbitmq

  paymentprocessor:
    build:
      context: ./PaymentProcessor
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
      - rabbitmq

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    ports:
      - "15672:15672" 
      - "5672:5672"   

volumes:
  postgres_data:
