services:
  publicapi:
    build:
      context: ./PublicApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - rabbitmq

  paymentprocessor:
    build:
      context: ./PaymentProcessor
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
      - rabbitmq

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: postgres:latest
    environment:
      POSTGRES_DB: GeoPagos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # Management interface
      - "5672:5672"    # Default RabbitMQ port
      
volumes:
  postgres_data:
