version: '3.8'
services:
  publicapi:
    build:
      context: ./PublicApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  paymentprocessor:
    build:
      context: ./PaymentProcessor
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  test:
    build:
      context: ./TestPaymentProcessorApp
      dockerfile: Dockerfile