services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: ./TestPaymentProcessorApp/Dockerfile
    depends_on:
      - db
