# name: Build .NET projects

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v2
#         with:
#           dotnet-version: '6.0'

#       - name: Build solution
#         run: dotnet build PaymentProcessorApp.sln --configuration Release
